name: "@fireproof/core-publish"
description: "setup  runtime"
runs:
  using: "composite"
  steps:
    - name: publish
      shell: bash
      run: |
        rm -f ~/.npmrc
        find . \( -name .npmrc -o -name npmrc-smoke \) -print0 | xargs -0 rm -f --
        npm install -g npm@11
        npm --version
        git fetch --tags --force > /dev/null 2>&1
        pnpm run -r publish --registry https://registry.npmjs.org/ --npm npm

#       echo git checkout origin/main ./allowed_signers
#       echo git config --local --add gpg.ssh.allowedSignersFile ./allowed_signers
#       echo "GITHUB_REF->"$GITHUB_REF
#       echo git tag -v $(git describe --tags --abbrev=0)
