name: "setup-runtime"
description: "setup  runtime"
# inputs:
# your inputs here
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v5
      name: Install pnpm
      with:
        run_install: false
        version: 10

    #    - uses: useblacksmith/setup-node@v5
    - uses: actions/setup-node@v5
      with:
        node-version: "24"
        cache: pnpm

    - name: generate-https-certs
      shell: bash
      run: |
        sudo apt-get install -y mkcert libnss3-tools
        mkcert -install
        cd vibes.diy/pkg
        mkcert "*.localhost.vibesdiy.net" localhost
