// Tailwind utility-class → canonical CSS variable remap.
//
// Apps generated by the LLM mix two patterns: explicit `rounded-[var(--radius)]`
// (already responds to canonical edits via CSS cascade), and literal Tailwind
// utilities like `rounded-md`, `p-4`, `text-lg` (frozen values from Tailwind's
// scale, would NOT respond). This stylesheet rewrites the literal utilities to
// resolve through `var(--canonical, <fallback>)` so the modal's structural
// edits (--radius, --spacing, --font-family, etc.) flow through to both
// patterns. Injected once per iframe boot; the CSS variables update through
// the existing color-override pipeline so no second injection is needed.
//
// Scope decisions:
//   - rounded-full / rounded-none: preserved (semantic, not a scale step)
//   - border-0 / border-2 / border-4 / border-8: preserved (explicit weights)
//   - font-serif: preserved (no canonical serif token)
//   - p-0 / m-0 / gap-0: preserved (explicit zero)
//   - text-base maps directly to var(--font-size-base); other sizes scale
//     proportionally to Tailwind's defaults so visual hierarchy survives a
//     base-size change.

// Tailwind's spacing scale step values (units of 0.25rem). Generates p-*, m-*,
// gap-*, space-*-* utilities. n=4 corresponds to the canonical --spacing
// default (1rem) so the ratio is n/4.
const SPACING_STEPS = [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, 28, 32, 36, 40, 44, 48];

// Tailwind's font-size scale, expressed as ratios off `text-base` (1rem).
// Keeps the proportions when the user changes --font-size-base.
const FONT_SIZE_SCALE: [string, number][] = [
  ["xs", 0.75],
  ["sm", 0.875],
  ["base", 1],
  ["lg", 1.125],
  ["xl", 1.25],
  ["2xl", 1.5],
  ["3xl", 1.875],
  ["4xl", 2.25],
  ["5xl", 3],
  ["6xl", 3.75],
  ["7xl", 4.5],
  ["8xl", 6],
  ["9xl", 8],
];

// CSS class names can't contain a literal `.`, so Tailwind escapes the dot in
// fractional spacing (`p-0.5` → `.p-0\.5`).
function escapeClass(n: number): string {
  return String(n).replace(/\./g, "\\.");
}

function spacingExpr(n: number): string {
  const ratio = n / 4;
  // Round to 4 decimals to keep the CSS readable; ratio is always a multiple
  // of 0.125 so 4 decimals is exact for the scale we emit.
  const r = Number.isInteger(ratio) ? String(ratio) : ratio.toFixed(4).replace(/0+$/, "").replace(/\.$/, "");
  return `calc(var(--spacing, 1rem) * ${r})`;
}

export function generateTailwindRemapCss(): string {
  const out: string[] = [];

  // ────────────── Border radius
  out.push(`.rounded { border-radius: var(--radius, 0.5rem) !important; }`);
  out.push(`.rounded-sm { border-radius: var(--radius-sm, 0.25rem) !important; }`);
  out.push(`.rounded-md { border-radius: var(--radius, 0.5rem) !important; }`);
  out.push(`.rounded-lg { border-radius: var(--radius-lg, 1rem) !important; }`);
  out.push(`.rounded-xl { border-radius: var(--radius-lg, 1rem) !important; }`);
  out.push(`.rounded-2xl { border-radius: calc(var(--radius-lg, 1rem) * 1.25) !important; }`);
  out.push(`.rounded-3xl { border-radius: calc(var(--radius-lg, 1rem) * 1.5) !important; }`);
  // rounded-full / rounded-none preserved.

  // Per-corner overrides — same scaling rules as the all-corner variants.
  const corners = ["t", "r", "b", "l", "tl", "tr", "br", "bl"];
  const cornerProp: Record<string, string[]> = {
    t: ["border-top-left-radius", "border-top-right-radius"],
    r: ["border-top-right-radius", "border-bottom-right-radius"],
    b: ["border-bottom-left-radius", "border-bottom-right-radius"],
    l: ["border-top-left-radius", "border-bottom-left-radius"],
    tl: ["border-top-left-radius"],
    tr: ["border-top-right-radius"],
    br: ["border-bottom-right-radius"],
    bl: ["border-bottom-left-radius"],
  };
  const radiusSizes: [string, string][] = [
    ["sm", "var(--radius-sm, 0.25rem)"],
    ["", "var(--radius, 0.5rem)"],
    ["md", "var(--radius, 0.5rem)"],
    ["lg", "var(--radius-lg, 1rem)"],
    ["xl", "var(--radius-lg, 1rem)"],
  ];
  for (const c of corners) {
    for (const [size, val] of radiusSizes) {
      const cls = size === "" ? `.rounded-${c}` : `.rounded-${c}-${size}`;
      const props = cornerProp[c].map((p) => `${p}: ${val} !important;`).join(" ");
      out.push(`${cls} { ${props} }`);
    }
  }

  // ────────────── Spacing scale (padding / margin / gap / space-*)
  for (const n of SPACING_STEPS) {
    const cls = escapeClass(n);
    const expr = spacingExpr(n);
    out.push(`.p-${cls} { padding: ${expr} !important; }`);
    out.push(`.px-${cls} { padding-left: ${expr} !important; padding-right: ${expr} !important; }`);
    out.push(`.py-${cls} { padding-top: ${expr} !important; padding-bottom: ${expr} !important; }`);
    out.push(`.pt-${cls} { padding-top: ${expr} !important; }`);
    out.push(`.pr-${cls} { padding-right: ${expr} !important; }`);
    out.push(`.pb-${cls} { padding-bottom: ${expr} !important; }`);
    out.push(`.pl-${cls} { padding-left: ${expr} !important; }`);
    out.push(`.ps-${cls} { padding-inline-start: ${expr} !important; }`);
    out.push(`.pe-${cls} { padding-inline-end: ${expr} !important; }`);

    out.push(`.m-${cls} { margin: ${expr} !important; }`);
    out.push(`.mx-${cls} { margin-left: ${expr} !important; margin-right: ${expr} !important; }`);
    out.push(`.my-${cls} { margin-top: ${expr} !important; margin-bottom: ${expr} !important; }`);
    out.push(`.mt-${cls} { margin-top: ${expr} !important; }`);
    out.push(`.mr-${cls} { margin-right: ${expr} !important; }`);
    out.push(`.mb-${cls} { margin-bottom: ${expr} !important; }`);
    out.push(`.ml-${cls} { margin-left: ${expr} !important; }`);
    out.push(`.ms-${cls} { margin-inline-start: ${expr} !important; }`);
    out.push(`.me-${cls} { margin-inline-end: ${expr} !important; }`);

    out.push(`.gap-${cls} { gap: ${expr} !important; }`);
    out.push(`.gap-x-${cls} { column-gap: ${expr} !important; }`);
    out.push(`.gap-y-${cls} { row-gap: ${expr} !important; }`);

    // `space-x-N > * + *` adds left-margin between siblings; same for y.
    out.push(`.space-x-${cls} > :not([hidden]) ~ :not([hidden]) { margin-left: ${expr} !important; }`);
    out.push(`.space-y-${cls} > :not([hidden]) ~ :not([hidden]) { margin-top: ${expr} !important; }`);
  }

  // ────────────── Font size (scaled off --font-size-base)
  for (const [name, ratio] of FONT_SIZE_SCALE) {
    const expr = `calc(var(--font-size-base, 1rem) * ${ratio})`;
    out.push(`.text-${name} { font-size: ${expr} !important; }`);
  }

  // ────────────── Font family
  out.push(
    `.font-sans { font-family: var(--font-family, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif) !important; }`
  );
  out.push(
    `.font-mono { font-family: var(--font-family-mono, ui-monospace, 'JetBrains Mono', Menlo, monospace) !important; }`
  );
  // font-serif preserved (no canonical token for serifs).

  // ────────────── Border width (single, unitless default)
  out.push(`.border { border-width: var(--border-width, 1px) !important; }`);
  // border-0 / border-2 / border-4 / border-8 preserved as explicit choices.

  return out.join("\n");
}
