import { defineCollection, z } from 'astro:content';
import { file } from 'astro/loaders';

// The gallery data is a single JSON array (generated by scripts/extract-data.mjs
// from ../index.html). Astro's file() loader turns it into a typed collection.
// Each entry's `id` is the slug of its path (matches previews/<id>.png and
// tools/shoot.py).
const artifacts = defineCollection({
  loader: file('src/data/artifacts.json'),
  schema: z.object({
    id: z.string(),
    name: z.string(),
    path: z.string(),
    tags: z.array(z.string()),
    source: z.string(),
    loading: z.enum(['esm', 'script']).optional(),
    bucket: z.enum(['mine', 'collected', 'templates', 'starters']),
    featured: z.boolean().default(false), // publisher highlight (not per-viewer faves)
    size: z.number().default(0), // bytes of the source .html
    preview: z.string(),
  }),
});

export const collections = { artifacts };
